apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ramen.fullname" . }}-env
  labels: {{- include "ramen.labels" . | nindent 4 }}
data:
  RAMEN_GROUP: {{ .Values.group | quote }}
  RAMEN_ENV: {{ .Values.environment | quote }}
  RAMEN_NODE_PORT: {{ .Values.worker.port | quote }}
  RAMEN_BUCKET: {{ printf "%s/%s" .Values.worker.bucketPath .Values.group | quote }}
  {{- range $k, $v := .Values.worker.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $k, $v := .Values.console.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
