{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ramen.fullname" . }}-console
  labels: {{- include "ramen.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.console.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.console.service.type }}
  selector: { app.kubernetes.io/instance: {{ .Release.Name }}, ramen.io/role: console }
  ports: [{ name: http, port: {{ .Values.console.port }}, targetPort: http }]
{{- end }}
