apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ramen.fullname" . }}-secrets
  labels: {{- include "ramen.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.worker.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $k, $v := .Values.console.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
