{{- if not .Values.console.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: ramen-console
  labels: {{- include "ramen.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.console.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
