apiVersion: v1
kind: Service
metadata:
  name: console
  labels: {{- include "ramen.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "ramen.selector" . | nindent 4 }}
  ports: [{ name: http, port: 80, targetPort: http }]
