apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: {{- include "ramen.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.provider "aws" }}
    eks.amazonaws.com/role-arn: {{ include "ramen.roleArn" . }}
    {{- else }}
    iam.gke.io/gcp-service-account: {{ include "ramen.gsa" . }}
    {{- end }}
