apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels: {{- include "ramen.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "ramen.gsa" . }}
