# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ramen_proto/ramen/v1/admin.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ramen_proto/ramen/v1/admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ramen_proto/ramen/v1/admin.proto\x12\x08ramen.v1\"\x0f\n\rReloadRequest\"\x1a\n\nLoadResult\x12\x0c\n\x04json\x18\x01 \x01(\x0c\"\x10\n\x0eMetricsRequest\"\x1c\n\x0cMetricsReply\x12\x0c\n\x04json\x18\x01 \x01(\x0c\x32}\n\x05\x41\x64min\x12\x37\n\x06Reload\x12\x17.ramen.v1.ReloadRequest\x1a\x14.ramen.v1.LoadResult\x12;\n\x07Metrics\x12\x18.ramen.v1.MetricsRequest\x1a\x16.ramen.v1.MetricsReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ramen_proto.ramen.v1.admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELOADREQUEST']._serialized_start=46
  _globals['_RELOADREQUEST']._serialized_end=61
  _globals['_LOADRESULT']._serialized_start=63
  _globals['_LOADRESULT']._serialized_end=89
  _globals['_METRICSREQUEST']._serialized_start=91
  _globals['_METRICSREQUEST']._serialized_end=107
  _globals['_METRICSREPLY']._serialized_start=109
  _globals['_METRICSREPLY']._serialized_end=137
  _globals['_ADMIN']._serialized_start=139
  _globals['_ADMIN']._serialized_end=264
# @@protoc_insertion_point(module_scope)
