apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "rw.ns" . }}
  labels: {{- include "rw.labels" . | nindent 4 }}
  {{- if ne .Values.serviceAccount.gsa "-" }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "rw.gsa" . }}
  {{- end }}
